export const QUERIES = {
  // EVENTS
  LIST_EVENTS: "LIST_EVENTS",
};

export const ADM_QUERIES = {
  // MEMBROS
  LIST_MEMBROS_ADM: "LIST_MEMBROS_ADM",

  // EVENTS
  LIST_EVENTS_ADM: "LIST_EVENTS_ADM",

  // DONATIONS
  LIST_DONATIONS_ADM: "LIST_DONATIONS_ADM",

  // MINISTERIOS
  LIST_MINISTERIOS_ADM: "LIST_MINISTERIOS_ADM",
};
